/************************************************************************************* 

Program Name           : 007_mean_panel_1_consistent_Y_1.sas   

Path                   : sg1\007_mean_panel_consistent_Y

Purpose                : Mean Panel for each Treatment Group with Consistent Y Axis
                                                    
Input Datasets/Views   : Input data is generated by this program itself.

Macro calls external   : None

Production Outputs     : &Program..rtf  
                         &Program..pdf

Qualification Outputs  :  Dir_.means

Program Flow           :  1) Set SAS options and style template libname. 
                          2) Set global macro variable  
                          3) Define titles and footnotes, adjust for RTF and PDF width.   
                          4) Build formats                                                                   
                          5) Generate data.  
                          6) Generate the statistics and print results.  
                          7) Compute Y axis value for Subject Counts. 
                          8) Define macro to call SGPANEL.
                          9) Set ODS graphics on and specify required ODS graphics 
                             parameters for PDF                    
                         10) Run the SG code with the macro. Close graphic output PDF
                             and SGE file and write to disk.   
                         11) Reset  ODS graphics options and set RTF file options.  
                         12) Run the SG code with the macro. Close RTF graphic output and
                             write to disk. 
                         13) Delete temporary PNG file. 
                         
User Documentation      : Please see Biometrics Programming Training Wiki  
                        
Mod#    Ver#    Date            Username        Description
---     ----    -------         --------        ---------------------------------------------------
001     1.00    5/11/26         dgianneschi     Created program
*********************************************************************************************/
*-----------------------------------------------------------------------------------
 1) Set SAS options and style template libname.                      (template code)
 -----------------------------------------------------------------------------------;
 Options missing='-' nodate nonumber center nobyline label
         PAPERSIZE=Letter ORIENTATION=LANDSCAPE;

 libname ods_ '\sg1\000_style_template' access=readonly;
  
 ods path work.templates(update) ods_.templates(read) SASHelp.TmplMst(read);

*-----------------------------------------------------------------------------------
 2) Set global variables.                                            (template code)
 -----------------------------------------------------------------------------------;
 libname Dir_ '.';
 %let Dir_      = %sysfunc(pathname(Dir_)); 
 %let Program_  =007_mean_panel_1_consistent_Y;
 %let Style_RTF = US_Landscape_SG_Color; 

*-----------------------------------------------------------------------------------  
 3) Set titles and footnotes, adjust for RTF and PDF width.(template/functional code)
 -----------------------------------------------------------------------------------*;
 %macro titles(pdf=Y);
    title1 j=r h=7 pt 'Avidity Biosciences, Inc.';
    title2 j=r h=7 pt 'Study AV-US-xxx-xxx';
    title3  h=9 pt bold 'Figure 14-1.1.2. Laboratory Data by Treatment Group ';
    title4  h=9 pt bold " Mean Ambisome ~{unicode '00AE'x} by Study Week";
    footnote1 j=l h=7 pt "______________________________________________________________________"
                         "_____________________________________________________________________";
    footnote2 j=l h=7 pt "~{unicode '00B9'x} Study Week is defined as Saturday to Sunday";
    footnote3 j=l h=7 pt "Vertical lines represent the confidence interval around the mean (alpha=0.05)";
    footnote4 j=l h=7 pt "Data Extracted: program_generated   " 
                   "Source: &Program_..sas   "
                   "Output file: &Program_..rtf &sysdate &systime ";
 %mend titles;
    
%titles;
                  
*-----------------------------------------------------------------------------------
 4) Build formats                                                    (template code)
 -----------------------------------------------------------------------------------;
 proc format;
     value trtgroup 
           0='1:Placebo (N=100)'
           1='2:AVID001 10mg QD (N=100)'
           2='3:AVID001 20mg QD (N=100)'
           3='4:AVID001 30mg QD (N=100)'
           4='5:AVID001 40mg QD (N=100)'
           5='6:AVID001 50mg QD (N=100)'         
      ;    
 run;

*-----------------------------------------------------------------------------------
 5) Generate data.                                                 (functional code)    
 -----------------------------------------------------------------------------------;
 data labs;
   do trtgroup=0 to 5;
      length panel $ 40;
      panel=put(trtgroup,trtgroup.);
      do visit=0 to 6;
         do subject=1 to 100;
            subjid=subject*1000+trtgroup;
            lbdesc='ALB';
            lbstresn=(30+sqrt(10)*rannor(5451)) + 
                     (trtgroup*2) + 
                     ((subjid*.001) + sqrt(5)*rannor(75451)) +
                      (visit);  
            output;
         end;
      end;
   end;
 run;              
 
 proc sort data=labs;
    by lbdesc panel visit;
 run;

*-----------------------------------------------------------------------------------
 6) Generate the statistics and print results.                       (template code)    
 -----------------------------------------------------------------------------------;
 proc means data=labs nway noprint;
    var lbstresn;
    output out=Dir_.means n=n nmiss=nmiss mean=mean median=median min=min max=max range=range 
                          std=std stderr=stdmean uclm=uclm lclm=lclm q1=q1 q3=q3;
    by lbdesc panel visit;
 run;

 proc print data=Dir_.means;   
    var lbdesc panel visit n nmiss mean std uclm lclm q1 q3; 
 run;
 
*-----------------------------------------------------------------------------------
 7) Compute Y axis value for Subject Counts.                          (template code)    
 -----------------------------------------------------------------------------------;
 proc sql;   
   select min (lclm), max (uclm) into: ymin, :ymax 
   from Dir_.means

   quit;

data means;
   set Dir_.means;
   ymax=&ymax;
   ymin=&ymin;
   Y_offset=(ymax - ymin)/50;
   Y_n_subj= Ymin -(12*Y_offset);   
   nsubj=put(n,3.); 
   if visit=0 then do;
      n_subj_label="Number of Subjects:";   
      X_n_subj_label=0.75;
      Y_n_subj_label=&Ymin-(5*Y_offset);         
   end;   
 run;

*----------------------------------------------------------------------------------  
 8) Call SGPANEL.                                                  (template code)
 ----------------------------------------------------------------------------------  
 Define a macro which will excute the SG procedure code two times.
 UNISCALE option of the PANELBY statement controls = COLUMN | ROW | ALL 
 scales the shared axes in the panel to be identical.
 Specify one of the following values:
    COLUMN - scales all of the column axes in the panel to be identical.
       ROW - scales all of the row axes in the panel to be identical.
       ALL - scales all of the column axes to be identical, and also scales all
             of the row axes to be identical. 
 ----------------------------------------------------------------------------------*;
 %macro loop;
    proc sgpanel data = means nocycleattrs noautolegend ;

        panelby panel / columns=3 novarname uniscale=all  ;  
                                         /* uniscale=row for consistent Y*/                     
        rowaxis label="Mean Ambisome ~{unicode '00AE'x} (g\l)" 
                type=linear grid  offsetmin=0.05 offsetmax=0.05; 

        colaxis label="Study Week~{unicode '00B9'x}" type=linear grid
                offsetmin=0.10 offsetmax=0.05 values=(0 to 6 by 1);

        scatter y=mean x=visit /
               group=panel markerattrs=(size=0.01)
               yerrorlower=LCLM  yerrorupper=UCLM 
               errorbarattrs=(pattern=1 thickness=1px);

        series y=mean x=visit /  
              group=panel lineattrs=(thickness=2px);

        scatter x=x_n_subj_label y=y_n_subj_label / markerchar=n_subj_label;

        scatter x=visit y= y_n_subj / markerchar=nsubj;

   run;  
%mend loop;

*----------------------------------------------------------------------------------  
 9) Set ODS graphics on and specify required ODS graphics parameters to create a
    PDF output and an SGE file for presentation purposes.            (template code) 
 -----------------------------------------------------------------------------------;
 ods graphics on / reset=all height=5.75in width=9.00in imagemap=on border=off 
                     imagename="&Program_" ; /* For PNG file type */
 
 ods noproctitle escapechar='~';
 
 ods pdf 
        notoc
        file         = "&Program_..pdf"      /* pdf File Name */
        style        = &Style_RTF            /* ODS style template */
        dpi          = 300                   /* Publication quality resolution */
        ;
      
*----------------------------------------------------------------------------------  
 10) Run the SG code with the macro. Close graphic output PDF and SGE
     file and write to disk.                                        (template code)
 ----------------------------------------------------------------------------------;
 %loop;
 
 ods pdf      close;                        * Output PDF file ;

 *----------------------------------------------------------------------------------  
  11) Reset  ODS graphics options and set RTF file options.           (template code)
      RTF title is kept outside the graph to allow editing in WORD.
  -----------------------------------------------------------------------------------;
  ods graphics on / reset=all height=5.50in width=9.00in imagemap=on border=off 
                   imagename="&Program_" ; /* For PNG file type */

  ods noproctitle escapechar='~';

  ods rtf 
    nogtitle                              /* Put title in RTF text outside of graph */      
    bodytitle  
    notoc_data 
    file          = "&Program_..rtf"      /* RTF File Name */
    style         = &Style_RTF            /* ODS style template */
    headery       = 1080                  /* 0.75in space shared with top margin */
    footery       = 360                   /* 0.25in space shared with bottom margin */
    image_dpi     = 300
 ;

*----------------------------------------------------------------------------------  
 12) Run the GTL program with proc sgrender. Close graphic output RTF
     file and write to disk.                                        (template code)
 ----------------------------------------------------------------------------------;     
 %loop;
 
 ods rtf      close;                        * Output RTF file ;
 ods graphics off;

*----------------------------------------------------------------------------------  
 13) Delete temporary PNG file.                                      (template code)
 ----------------------------------------------------------------------------------;
 %let rc=%sysfunc(filename(png,&Program_..png));
 %let sysrc=%sysfunc(fdelete(&png));
 %let rc=%sysfunc(filename(png,SGPanel.png));
 %let sysrc=%sysfunc(fdelete(&png));







