/************************************************************************************* 

Program Name           : _004_kmplot_increasing_1.sas  

Path                   : sg1\004_kmplot_increasing\

Purpose                : Kaplan-Meier Plot 

Input Datasets/Views   : Input data is generated by this program itself.

Macro calls external   : None

Production Outputs     : &Program..rtf  
                         &Program..pdf
                         &Program..sge
                         
Qualification Outputs  : &Program._qrt.sas7bdat    - Quartiles - Median and 95% CI 
                         &Program._tst.sas7bdat    - Log Rank Homgeneaity Test 
                         &Program._sg.sas7bdat     - Statistical Graphic output dataset

Program Flow            : 1) Set SAS options and style template libname
                          2) Set global variables.   
                          3) Generate data
                          4) Run proc lifetest to get output datsets.                         
                          5) Put median, median CIs, into treatement format.                  
                          6) Put pvalue into macro variables.                                 
                          7) Run proc lifetest to get SG output datset.                       
                          8) Post process SG output datsets.                                  
                              a) Offset error bars
                              b) Delete error bar if collapsed to a single line 
                              c) Offset censors  
                          9) Block plot processing for "Subject at risk" 
                              a) sort by time
                              b) set missing character to blank 
                         10) Set ODS graphics on and specify required ODS graphics
                             parameters to create a PDF output and an SGE file for
                             presentation purposes.  
                         11) Define macro for titles and footnotes
                         12) Define the GTL program based on the SG dataset.   
                         13) Run the GTL program with proc sgrender. Close graphic output
                             PDF and SGE file and write to disk. 
                         14) Reset  ODS graphics options and set RTF file options.  
                             RTF title is kept outside the graph to allow editing in WORD.
                             Redefine titles.           
                         15) Run the GTL program with proc sgrender. Close graphic output RTF
                             file and write to disk. 
                         16) Delete temporary PNG file.                                      

Mod#    Ver#    Date            Username           Description
---     ----    -------         -----------        ------------------------------------------
001     1.00    15/11/26        dgianneschi        Create.
*********************************************************************************************/

*-----------------------------------------------------------------------------------
 1) Set SAS options.                                                 (template code)
 -----------------------------------------------------------------------------------;
 Options missing='-' nodate nonumber center nobyline label
         PAPERSIZE=Letter ORIENTATION=LANDSCAPE;


*-----------------------------------------------------------------------------------
 2)Set global variables.                                             (template code)
 -----------------------------------------------------------------------------------;
 libname Dir_ '.';

 %let Program_  = &JOBNAME;


*-----------------------------------------------------------------------------------
 3) Generate data

    This dataset has N=15 Control and N=15 Drug001 patients.

    Control patients have events throughout the the study and 5 events at week 10.

    Drug001 patients have no events until week 5 and one event each week thereafter.
    There are 5 censors at week 10.                                (functional code)
 -----------------------------------------------------------------------------------;

data event_data;
     label trtgroup=" ";
     label week="Time (Weeks)";
     label censor="Proportion of Subjects Surviving";
     trtgroup = 1; 
     do I=1 to 10;
        week     = I;
        subject  = I; 
        censor   = 0;
        output;
     end;
     do I=1 to 5;
        week     = 10;
        subject  = 10 + I; 
        censor   = 0;
        output;
     end;
     trtgroup = 2; 
     do I=1 to 5;
        week     = I;
        subject  = 100 + I; 
        censor   = 1;
        output;
     end;
     do I=6 to 10;
        week     = I;
        subject  = 100 + I; 
        censor   = 0;
        output;
     end;
     do I=1 to 5;
        week     = 10;
        subject  = 110 + I; 
        censor   = 1;
        output;
     end;
run;

*-----------------------------------------------------------------------------------
  4) Run proc lifetest to get output datsets.                        (template code)
 -----------------------------------------------------------------------------------;
 ods output quartiles = Dir_.&Program_._qrt(where=(percent=50)); 
 ods output HomTests  = Dir_.&Program_._tst ;
 
 proc lifetest data=event_data method=KM CONFTYPE=LINEAR;
      strata trtgroup / test=(LOGRANK);
      time week * censor(1) ;  
 run; 

*-----------------------------------------------------------------------------------
  5) Put median, median CIs, into treatement format.                 (template code)
 -----------------------------------------------------------------------------------;
 %let _medval1 = ;
 %let _medval2 = ;

 data _null_;
    set Dir_.&Program_._qrt;
        if trtgroup=1 & Percent=50 then do;
            call symput("_medval1",    "Median (95% CI)  " || trim(left(put(estimate,9.1))) || ' (' ||
                 trim(left(put(lowerlimit,9.1))) || ', ' || trim(left(put(upperlimit,9.1))) || ')' );
        end;
        if trtgroup=2 & Percent=50 then do;
            call symput("_medval2",    "Median (95% CI)  " || trim(left(put(estimate,9.1))) || ' (' ||
                 trim(left(put(lowerlimit,9.1))) || ', ' || trim(left(put(upperlimit,9.1))) || ')' );
        end;
 run;

 proc format;
    value
      trtgroup (notsorted)
           1="Control (N = 15)    &_medval1"
           2="Drug001 (N = 15)    &_medval2"
       ;
    
 run;

*-----------------------------------------------------------------------------------
  6) Put pvalue into macro variables.                                (template code)
 -----------------------------------------------------------------------------------;
 %let _p_value = ;

 data _null_;
    set Dir_.&Program_._tst;
        length _p_value $ 10;
        if ProbChiSq < .0001 then _p_value = "p < .0001";
                             else _p_value = "p = "||trim(left(put(probchisq,PVALUE6.4)));
        call symput("_p_value", 'Log Rank, '||_p_value);
 run;

*-----------------------------------------------------------------------------------
  7) Run proc lifetest to get SG output datset.                      (template code)
 -----------------------------------------------------------------------------------;
 ods graphics on;
 ods output survivalplot  =Dir_.&Program_._sg; 
 
 proc lifetest data=event_data method=KM CONFTYPE=LINEAR
      plots(only)=(survival(cl atrisk=0 to 10 by 1 strata=overlay test));
      strata trtgroup / test=(LOGRANK);
      time week *censor(1) ;  
      format trtgroup trtgroup.;
 run; 

*-----------------------------------------------------------------------------------
  8) Post process SG output datsets.                                 (template code)
     a) Offset error bars - a good offset amount for two treatments is 0.005*X_MAX
     b) Delete error bar if collapsed to a single line 
     c) Offset censors - a good offset amount for censors is 0.002*X_MAX
 -----------------------------------------------------------------------------------;
 data Dir_.&Program_._sg; 

     set Dir_.&Program_._sg;by stratumnum time;
     
     survival=1-survival;
     sdf_ucl=1-sdf_ucl;
     sdf_lcl=1-sdf_lcl;
     
     if SDF_UCL>. or SDF_LCL>. then do;
        if StratumNum=1 then x_err_bar=time-.05;
        if StratumNum=2 then x_err_bar=time+.05;
        if SDF_UCL=SDF_LCL then do;
           SDF_UCL=.; SDF_LCL=.;  /* Delete error bar from plot where the top and bottom 
                                     plot as a line on the survival curve*/
        end;
     end;

     if censored>. then do;
        censored=1-censored;
        if time=lag(time) and stratum=lag(stratum) then censor_count+1;
        Y_censored = censored +.02; 
        X_censored = TIME - (censor_count * .02);  
        marker_censored="|";
     end;
     else censor_count=1;

     if StratumNum=1 then at_risk_1=atrisk;
     if StratumNum=2 then at_risk_2=atrisk;
 run;
 *----------------------------------------------------------------------------------  
   9) Block plot processing for "Subject at risk" 
      a) sort by time
      b) set missing character to blank                              (template code)
  -----------------------------------------------------------------------------------;
  proc sort;by time;
  options missing=' ';

 *----------------------------------------------------------------------------------  
      10) Set ODS graphics on and specify required ODS graphics parameters to create a
          PDF output and an SGE file for presentation purposes.       (template code) 
  -----------------------------------------------------------------------------------;
  ods graphics on / reset=all height=6.00in width=9.00in imagemap=on border=off 
                    imagename="&JOBNAME" ; /* For PDF and SGE file type */

 
  ods pdf 
      notoc 
      file          = "&JOBNAME..pdf"      /* pdf File Name */
      style         = &_Style_Land         /* ODS style template */
      dpi           = 300
        ;
 
    
 *-------------------------------------------------------------------------------------
  11) Define titles.                                         (template/functional code)
  -------------------------------------------------------------------------------------;
 title1 j=r h=1.0 "&prtcmpny.";
 title2 j=r h=1.0 "&prtstudy.";
 title3 h=3.0 'Figure 14-1.1.2. Kaplan-Meier Estimates of Time to Death ';      
 footnote;
 
 
*----------------------------------------------------------------------------------  
 12) Define the GTL program based on the SG dataset.                 (template code)
      Define footnotes within GTL code.
 ----------------------------------------------------------------------------------*;
 proc template;                                                                                                                       
                                                                         
 define statgraph Graphics._sg;

   mvar _p_value;

   BeginGraph;
      layout overlay / 
          xaxisopts=(label="Study Week" 
                     linearopts=(viewmin=-0.05 viewmax=10.05 
                     tickvaluelist=(0 1 2 3 4 5 6 7 8 9 10))) 

          yaxisopts=(label="Time to Death Probability"  OFFSETMIN=0.10  
                     linearopts=(viewmin=0 viewmax=1.00 
                     tickvaluelist=(0 .1 .2 .3 .4 .5 .6 .7 .8 .9 1.0)));

         scatterplot y=SURVIVAL x=x_err_bar /
               group=STRATUM index=STRATUMNUM   markerattrs=(size=0.01)
               yerrorlower=SDF_LCL  yerrorupper=SDF_UCL 
               errorbarattrs=(pattern=1 thickness=1px);
         
         stepplot y=SURVIVAL x=TIME / primary=true
               group=STRATUM index=STRATUMNUM name="Survival" display=(markers)
               lineattrs=(thickness=2px);

         scatterplot y=Y_CENSORED x=X_CENSORED / markercharacter=marker_censored;

         entry _p_value /  
               autoalign=(TOPLEFT)  Opaque=true pad=(top=30px left=30px);

         entry "Number of Subjects at Risk:" / 
               autoalign=(BOTTOMLEFT) Opaque=true pad=(top=5px);

         innermargin / align=bottom;
               blockplot x=time block=AT_RISK_2 / 
                  label='2:' display=(label values)
                  valuehalign=start valuefitpolicy=truncate labelposition=left labelattrs=GRAPHDATA2 (size=7pt)
                  valueattrs=GRAPHDATA2 (size=7pt) ;
               blockplot x=time block=AT_RISK_1 / 
                  label='1:' display=(label values)
                  valuehalign=start valuefitpolicy=truncate labelposition=left labelattrs=GRAPHDATA1 (size=7pt) 
                  valueattrs=GRAPHDATA1 (size=7pt);
        endinnermargin;
         
         DiscreteLegend "Time to Death" / title=" " autoalign=(bottom) location=outside;

      endlayout;

      entryfootnote halign=left textattrs=(size=7pt)
                "_________________________________________________________________________________"
                "_________________________________________________________________________________";
                 
      entryfootnote halign=left 
                "Censor indicated by vertical bar |.  " 
                "Error bar represents a 95% pointwise confidence interval for the time to death function.  "
                 / pad=(top=5px) textattrs=(size=8pt);

      entryfootnote halign=left 
                "Data Extracted: program_generated   " 
                "Source: ...&FOOT_JOBNAME   "
                "Output file: &JOBNAME..rtf &sysdate &systime "
                / pad=(top=5px) ;
  EndGraph;
 end;
 run;                                                                                                                       
  
*----------------------------------------------------------------------------------  
 13) Run the GTL program with proc sgrender. Close graphic output PDF and SGE
     file and write to disk.                                        (template code)
 ----------------------------------------------------------------------------------;
 proc sgrender data = Dir_.&Program_._sg template = Graphics._sg;
 run;

 ods pdf      close;                        * Output PDF file ;

*----------------------------------------------------------------------------------  
 14) Reset  ODS graphics options and set RTF file options.  RTF title is kept outside          
     the graph to allow editing in WORD.  Redefine titles.           (template code)
 -----------------------------------------------------------------------------------;
 ods graphics on / reset=all height=5.70in width=9.00in imagemap=on border=off 
                  imagename="&Program_" ; /* For RTF file type */

 ods rtf 
    nogtitle                              /* Put title in RTF text outside of graph */      
    bodytitle  
    notoc_data 
    file          = "&JOBNAME..rtf"       /* RTF File Name */
    style         = &_Style_Land          /* ODS style template */
    headery       = 1080                  /* 0.75in space shared with top margin */
    footery       = 360                   /* 0.25in space shared with bottom margin */
    image_dpi     = 300
 ;

*----------------------------------------------------------------------------------  
 15) Run the GTL program with proc sgrender. Close graphic output RTF
     file and write to disk.                                        (template code)
 ----------------------------------------------------------------------------------;     
 proc sgrender data = Dir_.&Program_._sg template = Graphics._sg;
 run;

 ods rtf      close;                        * Output RTF file ;
 ods graphics off;

*----------------------------------------------------------------------------------  
 16) Delete temporary PNG file.                                      (template code)
 ----------------------------------------------------------------------------------;
 %let rc=%sysfunc(filename(png,&JOBNAME..png));
 %let sysrc=%sysfunc(fdelete(&png));
 %let rc=%sysfunc(filename(png,SurvivalPlot.png));
 %let sysrc=%sysfunc(fdelete(&png)); 



