    /************************************************************************************* 

    Program Name           : kaplan_meier_panel_plot_1.sas  

    Path                   : sg1/

    Purpose                : Kaplan-Meier Panel Plot

    Input Datasets/Views   : Input data is generated by this program itself.

    Macro calls external   : None

    Production Outputs     : &Program..rtf  
                             &Program..pdf
                             &Program..sge
                             
    Qualification Outputs  : &Program._qrt.sas7bdat    - Quartiles - Median and 95% CI 
                             &Program._tst.sas7bdat    - Log Rank Homgeneaity Test 
                             &Program._sg.sas7bdat     - Statistical Graphic output dataset

    Program Flow           : 1) Set SAS options and style template libname
                             2) Set global macro variable that make code easier to read.
                             3) Generate data
                             4) Run proc lifetest to get output datsets.                         
                             5) Put median, median CIs, into treatement format.                  
                             6) Put pvalue into macro variables.                                 
                             7) Run proc lifetest to get SG output datset.                       
                             8) Post process SG output datsets.                                  
                                 a) Delete error bar if collapsed to a single line 
                                 b) Offset censors
                             9) Set ODS graphics on and specify required ODS graphics
                                parameters to create a PDF output and an SGE file for
                                presentation purposes.  
                            10) Define macro to set titles and footnotes, adjusting
                                for differences in RTF and PDF width. Run macro.
                            11) Define macro to run SGPANEL code. Run macro.
                            12) Close graphic output PDF and write to disk.       (template code)
                            13) Reset  ODS graphics options and set RTF file options.
                                RTF title is kept outside the graph to allow editing in WORD.
                            14) Delete temporary PNG file.                                

    Mod#    Ver#    Date            Username           Description
    ---     ----    -------         -----------        -----------------------------------------
    001     1.00    5/10/26         dgianneschi        Create.
    *********************************************************************************************/

    *-----------------------------------------------------------------------------------
     1) Set SAS option.                                                  (template code)
     -----------------------------------------------------------------------------------;
     Options missing='-' nodate nonumber center nobyline label mprint
             PAPERSIZE=Letter ORIENTATION=LANDSCAPE;
             
 
   *-----------------------------------------------------------------------------------
    2) Set location of validation file output and file name root.       (template code)
    -----------------------------------------------------------------------------------;
     libname Dir_ '.';
     %let Program_=&JOBNAME;
          
    *-----------------------------------------------------------------------------------
     3) Generate data                                                  (functional code)
     -----------------------------------------------------------------------------------
        This dataset has N=15 Control and N=15 Drug001 patients.

        Control patients have events throughout the the study and 5 events at week 10.

        Drug001 patients have no events until week 5 and one event each week thereafter.
        There are 5 censors at week 10.                                
     -----------------------------------------------------------------------------------;

    data event_data;
         label trtgroup=" ";
         label week="Time (Weeks)";
         label censor="Proportion of Subjects Surviving";
         trtgroup = 1; 
         do I=1 to 10;
            week     = I;
            subject  = I; 
            censor   = 0;
            output;
         end;
         do I=1 to 5;
            week     = 10;
            subject  = 10 + I; 
            censor   = 0;
            output;
         end;
         trtgroup = 2; 
         do I=1 to 5;
            week     = I;
            subject  = 100 + I; 
            censor   = 1;
            output;
         end;
         do I=6 to 10;
            week     = I;
            subject  = 100 + I; 
            censor   = 0;
            output;
         end;
         do I=1 to 5;
            week     = 10;
            subject  = 110 + I; 
            censor   = 1;
            output;
         end;
    run;

    *-----------------------------------------------------------------------------------
      4) Run proc lifetest to get output datsets.                        (template code)
     -----------------------------------------------------------------------------------;
     ods output quartiles  =Dir_.&Program_._qrt(where=(percent=50)); 
     ods output HomTests   =Dir_.&Program_._tst ;
   
     proc lifetest data=event_data method=KM CONFTYPE=LINEAR;
          strata trtgroup / test=(LOGRANK);
          time week * censor(1) ;  
     run; 

    *-----------------------------------------------------------------------------------
      5) Put median, median CIs, into treatement format.                 (template code)
     -----------------------------------------------------------------------------------;
     %let _medval1 = ;
     %let _medval2 = ;

     data _null_;
        set Dir_.&Program_._qrt;
            if trtgroup=1 & Percent=50 then do;
                call symput("_medval1",    "Median (95% CI)  " || trim(left(put(estimate,9.1))) || ' (' ||
                     trim(left(put(lowerlimit,9.1))) || ', ' || trim(left(put(upperlimit,9.1))) || ')' );
            end;
            if trtgroup=2 & Percent=50 then do;
                call symput("_medval2",    "Median (95% CI)  " || trim(left(put(estimate,9.1))) || ' (' ||
                     trim(left(put(lowerlimit,9.1))) || ', ' || trim(left(put(upperlimit,9.1))) || ')' );
            end;
     run;

     proc format;
        value
          trtgroup (notsorted)
               1="Control(N = 15) &_medval1"
               2="Drug001(N = 15) &_medval2"
           ;
        
     run;

    *-----------------------------------------------------------------------------------
      6) Put pvalue into macro variables.                                (template code)
     -----------------------------------------------------------------------------------;
     %let _p_value = ;

     data _null_;
        set Dir_.&Program_._tst;
            length _p_value $ 10;
            if ProbChiSq < .0001 then _p_value = "p < .0001";
                                 else _p_value = "p = "||trim(left(put(probchisq,PVALUE6.4)));
            call symput("_p_value", 'Log Rank, '||_p_value||'.  ');
     run;

    *-----------------------------------------------------------------------------------
      7) Run proc lifetest to get SG output datset.                      (template code)
     -----------------------------------------------------------------------------------;
     ods graphics on;
     ods output survivalplot  =Dir_.&Program_._sg; 
     
     proc lifetest data=event_data method=KM CONFTYPE=LINEAR
          plots(only)=(survival(cl atrisk=0 to 10 by 1 strata=overlay test));
          strata trtgroup / test=(LOGRANK);
          time week *censor(1) ;  
          format trtgroup trtgroup.;
     run; 

    *-----------------------------------------------------------------------------------
     8) Post process SG output datsets.                                 (template code)
        a) Delete error bar from plot where the top and bottom plot as a 
           line on the survival curve.
        b) Offset censors - a good offset amount for censors is 0.002*X_MAX
     -----------------------------------------------------------------------------------;
     data Dir_.&Program_._sg; 

         set Dir_.&Program_._sg;by stratumnum stratum time;

         if SDF_UCL>. or SDF_LCL>. then do;
            if SDF_UCL=SDF_LCL then do;
               SDF_UCL=.; SDF_LCL=.;  
            end;
         end;

         if censored>. then do;
            if time=lag(time) and stratumnum=lag(stratumnum) then censor_count+1;
            Y_censored = censored +.02; 
            X_censored = TIME - (censor_count * .02);  
            marker_censored="|";
         end;
         else censor_count=1;

         if time=0 then do;
            n_atrisk_label="Number of Subjects:";   
            x_at_risk=1.0;
            y_at_risk_label=-0.05;         
         end;   
         y_at_risk=-0.10;
     run;
     
     *----------------------------------------------------------------------------------  
      9) Set ODS graphics on and specify required ODS graphics parameters to create a
         PDF output and an SGE file for presentation purposes.            (template code) 
      -----------------------------------------------------------------------------------;
      ods graphics on / reset=all height=6.00in width=9.00in imagemap=on border=off 
                        imagename="&JOBNAME" ; /* For PDF and SGE file type */
    
      ods pdf 
           notoc
           file         = "&JOBNAME..pdf"       /* pdf File Name */
           style        = &_Style_Land          /* ODS style template */
           dpi          = 300                   /* Publication quality resolution */
           ;
           
      
    *-----------------------------------------------------------------------------------  
     10) Set titles and footnotes, adjust for RTF and PDF width.(template/functional code)
     -----------------------------------------------------------------------------------*;
     title1 j=r h=1.0 "&prtcmpny.";
     title2 j=r h=1.0 "&prtstudy.";
     %let title3=%str(Figure 14-1.1.2. Kaplan-Meier Estimates of Survival);
     title3 h=2.25 "&title3";
     footnote j=l  "_________________________________________________________________________________"
                   "_________________________________________________________________________________";
     footnote2 j=l "&_p_value  Censor indicated by vertical bar |.  " 
                   "Error bar represents a 95% pointwise confidence interval for the survivor function.  ";
     footnote3 j=l "Data Extracted: program_generated   " 
                   "Source: ...&FOOT_JOBNAME   "
                   "Output file: &JOBNAME..pdf  &sysdate &systime ";

    *----------------------------------------------------------------------------------  
     11) Define macro to run SGPANEL code.                              (template code)
     ----------------------------------------------------------------------------------*;    
     %macro gen_graph;
        proc sgpanel data = Dir_.&Program_._sg nocycleattrs noautolegend ;

            panelby stratum / columns=2 novarname uniscale=all  ;  

            rowaxis label="Survival Probability" type=linear grid  
                    offsetmin=0.11 offsetmax=0.05 values=(0 to 1.0 by 0.1);
            colaxis label="Study Week" type=linear grid
                    offsetmin=0.05 offsetmax=0.05 values=(0 to 10 by 1);

            scatter y=SURVIVAL x=TIME /
                   group=stratum markerattrs=(size=0.01)
                   yerrorlower=SDF_LCL  yerrorupper=SDF_UCL 
                   errorbarattrs=(pattern=1 thickness=1px);

            step y=SURVIVAL x=TIME /  
                  group=stratum lineattrs=(thickness=2px);

            scatter y=Y_CENSORED x=X_CENSORED / markerchar=marker_censored;

            scatter x=x_at_risk y=y_at_risk_label / markerchar=n_atrisk_label;

            scatter x=time y= y_at_risk / markerchar=atrisk ;
       run;  
    %mend gen_graph;
    
    %gen_graph;
    
    *----------------------------------------------------------------------------------  
     12) Close graphic output PDF and SGE file and write to disk.       (template code)
     ----------------------------------------------------------------------------------;
     ods pdf      close;                        * Output PDF file ;
     
    *----------------------------------------------------------------------------------  
     13) Reset  ODS graphics options and set RTF file options.           (template code)
         RTF title is kept outside the graph to allow editing in WORD.
     -----------------------------------------------------------------------------------;
      ods graphics on / reset=all height=5.70in width=9.00in imagemap=on border=off 
                        imagename="&JOBNAME" ; /* For PNG file type */
    
     title3 h=3.00 "&title3";
     
      ods rtf 
          nogtitle                              /* Put title in RTF text outside of graph */      
          bodytitle  
          notoc_data 
          file          = "&JOBNAME..rtf"       /* RTF File Name */
          style         = &_Style_Land          /* ODS style template */
          headery       = 1080                  /* 0.75in space shared with top margin */
          footery       = 360                   /* 0.25in space shared with bottom margin */
          image_dpi     = 300
       ;

     %gen_graph; 
     
     ods rtf      close;                        * Output RTF file ;
     ods graphics off;
    
    *----------------------------------------------------------------------------------  
     14) Delete temporary PNG file.                                      (template code)
     ----------------------------------------------------------------------------------;
    %let rc=%sysfunc(filename(png,&JOBNAME..png));
    %let rc=%sysfunc(fdelete(&png));
    %let rc=%sysfunc(filename(png,SGPanel.png));
    %let rc=%sysfunc(fdelete(&png)); 
    %let rc=%sysfunc(filename(png,SurvivalPlot.png));
    %let rc=%sysfunc(fdelete(&png));
