/************************************************************************************* 

Program Name           : _003_kmplot_sidak_1.sas  

Path                   : sg1/_003_kmplot_sidak/

Purpose                : Kaplan-Meier Plot 

Input Datasets/Views   : Input data is generated by this program itself.

Macro calls external   : None

Production Outputs     : &Program..rtf  
                         &Program..pdf
                         &Program..sge
                         
Qualification Outputs  : &Program._qrt.sas7bdat     - Quartiles - Median and 95% CI 
                         &Program._tst.sas7bdat     - Log Rank Homgeneaity Test 
                         &Program._sg.sas7bdat      - Statistical Graphic output dataset
                         &Program_._srvdif.sas7bdat - Sidak Adjusted Multiple Pairwise Test
 
Program Flow           : 1) Set SAS options and style template libname
                         2) Set global macro variable  
                         3) Create the format 
                         4) Generate data
                         5) Run proc lifetest to get output datsets.     
                         6) Put subject count, median, median CIs, into treatement format.
                         7) Redefine format with big N and Median (95% CI) 
                         8) Put overall log-rank p-value into a macro variable.                               
                         9) Put pairwise sidak adjusted p-values into a macro variables.
                        10) Run proc lifetest to get SG output datset.                       
                        11) Post process SG output datsets.                                  
                             a) Offset error bars
                             b) Delete error bar if collapsed to a single line 
                             c) Offset censors
                        12) Block plot processing for "Subject at risk" 
                             a) sort by time
                             b) set missing character to blank                               
                        13) Set ODS graphics on and specify required ODS graphics 
                            parameters to create a PDF output 
                            for presentation.  
                        14) Define titles.    
                        15) Define the GTL program based on the SG dataset.                 
                        16) Run the GTL program.                                             
                        17) Close PDF output file and write to disk.                    
                        18) Set ODS graphics options for RTF file
                        19) Run the GTL program.                                             
                        20) Close RTF output file and write to disk.                    
                        21) Delete temporary PNG files.                         

Mod#    Ver#    Date            Username           Description
---     ----    -------         -----------        ---------------------------------------------------
001     1.00    5/11/26         dgianneschi        Create.
*********************************************************************************************/

*-----------------------------------------------------------------------------------
 1) Set SAS options.                                                  (template code)
 -----------------------------------------------------------------------------------;
 Options missing='-' nodate nonumber center nobyline label
         PAPERSIZE=Letter ORIENTATION=LANDSCAPE;


*-----------------------------------------------------------------------------------
 2) Set location of validation file output and file name root.        (template code)
 -----------------------------------------------------------------------------------;
 libname Dir_ '.';
 %let Program_  =&JOBNAME;


*-------------------------------------------------------------------------------------
 3) Create the format                                                  (template code)
 -------------------------------------------------------------------------------------;
 proc format;
     value trt
     1='ALL'
     2='AML-Low Risk'
     3='AML-High Risk'
  ;
 run;

*-----------------------------------------------------------------------------------
 4) Generate data                                                  (functional code)                                        
 -----------------------------------------------------------------------------------;
 data BMT;
     input Group T Status;
     format trt trt.;
     label T='Disease Free Time';
     trt=group;
     datalines;
1 2081 0
1 1602 0
1 1496 0
1 1462 0
1 1433 0
1 1377 0
1 1330 0 
1  996 0
1  226 0
1 1199 0
1 1111 0
1  530 0
1 1182 0
1 1167 0
1  418 1
1  383 1
1  276 1
1  104 1
1  609 1
1  172 1
1  487 1
1  662 1
1  194 1
1  230 1
1  526 1
1  122 1
1  129 1
1   74 1
1  122 1
1   86 1
1  466 1
1  192 1
1  109 1
1   55 1
1    1 1
1  107 1
1  110 1
1  332 1
2 2569 0
2 2506 0
2 2409 0
2 2218 0
2 1857 0
2 1829 0
2 1562 0
2 1470 0
2 1363 0
2 1030 0
2  860 0
2 1258 0
2 2246 0
2 1870 0
2 1799 0
2 1709 0
2 1674 0
2 1568 0
2 1527 0
2 1324 0
2  957 0
2  932 0
2  847 0
2  848 0
2 1850 0
2 1843 0
2 1535 0
2 1447 0
2 1384 0
2  414 1
2 2204 1
2 1063 1
2  481 1
2  105 1
2  641 1
2  390 1
2  288 1
2  421 1
2   79 1
2  748 1
2  486 1
2   48 1
2  272 1
2 1074 1
2  381 1
2   10 1
2   53 1
2   80 1
2   35 1
2  248 1
2  704 1
2  211 1
2  219 1
2  606 1
3 2640 0
3 2430 0
3 2252 0
3 2140 0
3 2133 0
3 1238 0
3 1631 0
3 2024 0
3 1345 0
3 1136 0
3  845 0
3  422 1
3  162 1
3   84 1
3  100 1
3    2 1
3   47 1
3  242 1
3  456 1
3  268 1
3  318 1
3   32 1
3  467 1
3   47 1
3  390 1
3  183 1
3  105 1
3  115 1
3  164 1
3   93 1
3  120 1
3   80 1
3  677 1
3   64 1
3  168 1
3   74 1
3   16 1
3  157 1
3  625 1
3   48 1
3  273 1
3   63 1
3   76 1
3  113 1
3  363 1
run;
  
*-----------------------------------------------------------------------------------
  5) Run proc lifetest to get output datsets.                        (template code)
 -----------------------------------------------------------------------------------;
 ods output quartiles = Dir_.&Program_._qrt(where=(percent=50)); 
 ods output HomTests  = Dir_.&Program_._tst ;
 ods output SurvDiff  = Dir_.&Program_._srvdif ;

 proc lifetest data=BMT method=KM CONFTYPE=LINEAR;
      strata trt / test=(LOGRANK) adjust=sidak;
      time T * status(0) ;  
 run; 

*-----------------------------------------------------------------------------------
  6) Put subject count, median, median CIs, into treatement format.  (template code)
 -----------------------------------------------------------------------------------;
 proc means data=BMT noprint;
    var T;
    output out=count n=n max=max;
    by trt;
 run;

 data _null_;
    set count;
    nvar='N'||trim(left(put(trt,2.0)));
    call symput(nvar,trim(left(put(n,3.0))));
    maxvar='MAX'||trim(left(put(trt,2.0)));
    call symput(maxvar,trim(left(put(max,4.0))));
  run;
 %put Maximum Time For Each Treatment Group:;
 %put     max1 = &max1; 
 %put     max2 = &max2; 
 %put     max3 = &max3; 

 %let _medval1 = ;
 %let _medval2 = ;
 %let _medval3 = ;

 data _null_;
    set Dir_.&Program_._qrt;
        var_name='_medval'||trim(left(put(trt,2.0)));
        if Percent=50 then  
           call symput(var_name,trim(left(put(estimate,9.1))) || ' (' ||
                 trim(left(put(lowerlimit,9.1))) || ', ' || trim(left(put(upperlimit,9.1))) || ')' );
 run;
 %put Median (95% CI):;
 %put     _medval1 = &_medval1; 
 %put     _medval2 = &_medval2; 
 %put     _medval3 = &_medval3; 

*-------------------------------------------------------------------------------------
 7) Redefine format with big N and Median (95% CI)                     (template code)
 -------------------------------------------------------------------------------------;
 proc format;
     value group
     1="ALL (N=&N1) , &_medval1"
     2="AML-Low Risk (N=&N2) , &_medval2"
     3="AML-High Risk (N=&N3), &_medval3"
  ;
run;
 
 
*-----------------------------------------------------------------------------------
  8) Put overall log-rank p-value into a macro variable.              (template code)
 -----------------------------------------------------------------------------------;
 %let _p_value = ;

 data _null_;
    set Dir_.&Program_._tst;
        length _p_value $ 10;
        if ProbChiSq < .0001 then _p_value = "p < .0001";
                             else _p_value = "p = "||trim(left(put(probchisq,PVALUE6.4)));
        call symput("_p_value", 'Among Treatment Log Rank: '||_p_value);
 run;
 %put Log Rank p-value:;
 %put     _p_value = &_p_value; 
 
 
*-----------------------------------------------------------------------------------
  9) Put pairwise sidak adjusted p-values into a macro variables.    (template code)
 -----------------------------------------------------------------------------------;
 %let _pair1 = ;
 %let _pair2 = ;
 %let _pair3 = ;
 data pair;
      set Dir_.&Program_._srvdif;
      length _p_sidak $20 _pair $ 200;
      var_name='_pair'||trim(left(put(_n_,2.0)));
      if sidak < .0001 then _p_sidak = ": p < .0001";
                       else _p_sidak = ": p = "||trim(left(put(sidak,PVALUE6.4)));
      _pair=trim(left(put(stratum1,trt.)))||' / '||trim(left(put(stratum2,trt.)))||_p_sidak;
      call symput(var_name,trim(_pair));
 run;
 %put Pairwise sidak adjusted p-values:;
 %put     _pair1 = &_pair1; 
 %put     _pair2 = &_pair2; 
 %put     _pair3 = &_pair3; 


*-----------------------------------------------------------------------------------
 10) Run proc lifetest to get SG output datset.                      (template code)
 -----------------------------------------------------------------------------------;
 ods graphics on;
 ods output survivalplot  =Dir_.&Program_._sg; 
 
 proc lifetest data=BMT method=KM CONFTYPE=LINEAR
      plots(only)=(survival(cb=hw atrisk=0 to 2500 by 500 strata=overlay test));
      strata group / test=(LOGRANK) adjust=sidak;
      time T *status(0) ;  
      format group group.;
 run; 

*-----------------------------------------------------------------------------------
 11) Post process SG output datsets.                                 (template code)
     a) Offset error bars - a good offset amount for two treatments is 0.005*X_MAX
     b) Retain prior error bar from prior time point where there is data.
     c) Delete error bar if collapsed to a single line 
     d) Offset censors - a good offset amount for censors is 0.002*X_MAX
 -----------------------------------------------------------------------------------;
 data Dir_.&Program_._sg; 

     set Dir_.&Program_._sg;by stratumnum time;

     retain lag_HW_UCL lag_HW_LCL lag_SURVIVAL;

     if first.stratumnum then do;
        lag_HW_UCL  = .;
        lag_HW_LCL  = .;
        lag_SURVIVAL = .;
     end;
     
     if HW_UCL>.   then lag_HW_UCL   = HW_UCL;
     if HW_LCL>.   then lag_HW_LCL   = HW_LCL;
     if SURVIVAL>. then lag_SURVIVAL = SURVIVAL;

     if lag_HW_LCL>. or lag_HW_UCL>. then do;
        if StratumNum=1 and mod(time,500)=0 and time<=&max1 then x_err_bar=time-10;
        if StratumNum=2 and mod(time,500)=0 and time<=&max2 then x_err_bar=time;
        if StratumNum=3 and mod(time,500)=0 and time<=&max3 then x_err_bar=time+10;
        if lag_HW_UCL=lag_HW_LCL then do;
           lag_HW_UCL=.; lag_HW_LCL=.;  /* Delete error bar from plot where the top and bottom 
                                             plot as a line on the survival curve*/
        end;
     end;

     if censored>. then do;
        if time=lag(time) and stratum=lag(stratum) then censor_count+1;
        Y_censored = censored +.02; 
        X_censored = time - (censor_count * .02);  
        marker_censored="|";
     end;
     else censor_count=1;
                   
     if StratumNum=1 and mod(time,500)=0 then at_risk_1=atrisk;
     if StratumNum=2 and mod(time,500)=0 then at_risk_2=atrisk;
     if StratumNum=3 and mod(time,500)=0 then at_risk_3=atrisk;
  run;
  
 *----------------------------------------------------------------------------------  
  12) Block plot processing for "Subject at risk" 
      a) sort by time
      b) set missing character to blank                              (template code)
  -----------------------------------------------------------------------------------;
  proc sort;by time;
  options missing=' ';

 *----------------------------------------------------------------------------------  
  13) Set ODS graphics on and specify required ODS graphics parameters to create a
      PDF output and an SGE file for presentation purposes.            (template code) 
  -----------------------------------------------------------------------------------;
  ods graphics on / reset=all height=6.00in width=9.00in imagemap=on border=off 
                    imagename="&JOBNAME" ; /* For PDF and SGE files */

  ods pdf 
       notoc
       file         = "&JOBNAME..pdf"       /* pdf File Name */
       style        = &_Style_Land          /* ODS style template */
       dpi          = 300                   /* Publication quality resolution */
       ;

*-------------------------------------------------------------------------------------
 14) Define titles blank out footnotes from init process.    (template/functional code)
 -------------------------------------------------------------------------------------;
 title1 j=r h=1.0 "&prtcmpny.";
 title2 j=r h=1.0 "&prtstudy.";
 title3 h=3.0 'Figure 14-1.1.2. Kaplan-Meier Estimates of Time to Death';
 footnote;
 
 
*----------------------------------------------------------------------------------  
 15) Define the GTL program based on the SG dataset.                (template code)
 ----------------------------------------------------------------------------------*;
 proc template;                                                                                                                       
                                                                         
 define statgraph Graphics._sg;

   mvar _p_value _pair1  _pair2 _pair3 ;


   BeginGraph;
      layout overlay / 
          xaxisopts=(label="Study Week" 
                     linearopts=(viewmin=-10 viewmax=2580 
                     tickvaluesequence=( start=0 end=2500 increment=500)))
 
          yaxisopts=(label="Survival Probability"  OFFSETMIN=0.05  
               linearopts=(viewmin=0 viewmax=1.10 
               tickvaluelist=(0 .1 .2 .3 .4 .5 .6 .7 .8 .9 1.0)));

         scatterplot y=lag_SURVIVAL x=x_err_bar /
               group=STRATUM index=STRATUMNUM   markerattrs=(size=0.01)
               yerrorlower=lag_HW_LCL  yerrorupper=lag_HW_UCL 
               errorbarattrs=(pattern=1 thickness=1px);
         
         stepplot y=SURVIVAL x=TIME / primary=true
               group=STRATUM index=STRATUMNUM name="Survival" display=standard
               lineattrs=(thickness=2px);

         scatterplot y=Y_CENSORED x=X_CENSORED / markercharacter=marker_censored;

         entry halign=left _p_value / valign=TOP Opaque=true;

         entry halign=right _pair3 / valign=TOP pad=(top=45) Opaque=true ;
         entry halign=right _pair2 / valign=TOP pad=(top=30) Opaque=true ;
         entry halign=right _pair1 / valign=TOP pad=(top=15) Opaque=true ;
         entry halign=right 'Between Treatment, Sidak Adjusted, Log Rank:     ' /  
                                     valign=TOP              Opaque=true ;

         entry "Number of Subjects at Risk:" / 
               autoalign=(BOTTOMLEFT) Opaque=true;

         innermargin / align=bottom;
               blockplot x=time block=AT_RISK_3 / 
                  label='3:' display=(label values)
                  valuehalign=start valuefitpolicy=truncate labelposition=left labelattrs=GRAPHDATA3 (size=7pt)
                  valueattrs=GRAPHDATA3 (size=7pt) ;
               blockplot x=time block=AT_RISK_2 / 
                  label='2:' display=(label values)
                  valuehalign=start valuefitpolicy=truncate labelposition=left labelattrs=GRAPHDATA2 (size=7pt)
                  valueattrs=GRAPHDATA2 (size=7pt) ;
               blockplot x=time block=AT_RISK_1 / 
                  label='1:' display=(label values)
                  valuehalign=start valuefitpolicy=truncate labelposition=left labelattrs=GRAPHDATA1 (size=7pt) 
                  valueattrs=GRAPHDATA1 (size=7pt);
        endinnermargin;
         
         DiscreteLegend "Survival" / 
                  title="Treatment, Median(95% CI)" TITLEATTRS=(size=9pt weight=bold )
                  valign=bottom location=outside across=2 ;

      endlayout;

      entryfootnote halign=left  
          "_________________________________________________________________________________"
          "_________________________________________________________________________________";
                      
            
      entryfootnote halign=left textattrs=(size=8pt)
            "Censor indicated by vertical bar |.  " 
            "Error bar represents a Hall-Wellner 95% simulataneous confidence interval for the survivor function.  "
            / pad=(top=5px);

      entryfootnote halign=left 
            "Data Extracted: program_generated   " 
            "Source: ...&FOOT_JOBNAME   "
            "Output file: &JOBNAME..rtf &sysdate &systime "
            / pad=(top=5px) textattrs=(size=8pt);

   EndGraph;
 end;
 run;                                                                                                                       
  
*-----------------------------------------------------------------------------------
 16) Run the GTL program.                                            (template code)
 -----------------------------------------------------------------------------------;
 proc sgrender data = Dir_.&Program_._sg template = Graphics._sg;
 run;
 
*----------------------------------------------------------------------------------  
 17) Close graphic output files and write PDF and SGE fiels to disk.(template code)
 ----------------------------------------------------------------------------------;
 ods pdf      close;                        * Output PDF file ;

*----------------------------------------------------------------------------------  
 18) Run the GTL program with proc sgrender. Close graphic output PDF
     file and write to disk.                                        (template code)
 ----------------------------------------------------------------------------------;
 proc sgrender data = Dir_.&Program_._sg template = Graphics._sg;
 run;

 ods pdf      close;                        * Output PDF file ;

*----------------------------------------------------------------------------------  
 19) Reset  ODS graphics options and set RTF file options.  RTF title is kept outside          
     the graph to allow editing in WORD.  Increase size of title3.   (template code)
 -----------------------------------------------------------------------------------;
 ods graphics on / reset=all height=5.70in width=9.00in imagemap=on border=off 
                    imagename="&JOBNAME" ; /* For RTF file type */

 ods rtf 
     nogtitle                              /* Put title in RTF text outside of graph */      
     bodytitle  
     notoc_data 
     file          = "&JOBNAME..rtf"       /* RTF File Name */
     style         = &_Style_Land          /* ODS style template */
     image_dpi     = 300
     headery       = 1080                  /* 0.75in space shared with top margin */
     footery       = 360                   /* 0.25in space shared with bottom margin */
  ;


*----------------------------------------------------------------------------------  
 20) Run the GTL program with proc sgrender. Close graphic output RTF
     file and write to disk.                                        (template code)
 ----------------------------------------------------------------------------------;     
 proc sgrender data = Dir_.&Program_._sg template = Graphics._sg;
 run;

 ods rtf      close;                        * Output RTF file ;
 ods graphics off;

*----------------------------------------------------------------------------------  
 21) Delete temporary PNG file.                                      (template code)
 ----------------------------------------------------------------------------------;
 %let rc=%sysfunc(filename(png,&JOBNAME..png));
 %let sysrc=%sysfunc(fdelete(&png));
 %let rc=%sysfunc(filename(png,SurvivalPlot.png));
 %let sysrc=%sysfunc(fdelete(&png)); 


